.PHONY: help install-cli db db-reset migration migrate schema admin openapi api-types dev run test lint fmt checklist web-dev web-build web-check web-e2e

# `.env` is the one place the URL lives. The sqlx macros compile each query
# against this database, so `test` and `lint` make sure it exists first.
-include .env
DATABASE_URL ?= sqlite://.dev/bunker.db?mode=rwc
export DATABASE_URL

API_DIR := crates/bunker-api
MIGRATIONS := $(API_DIR)/migrations
SCHEMA := $(API_DIR)/schema.sql
# `sqlite://.dev/bunker.db?mode=rwc` becomes `.dev/bunker.db`.
DB_FILE := $(firstword $(subst ?, ,$(patsubst sqlite://%,%,$(DATABASE_URL))))
SQLX := DATABASE_URL="$(DATABASE_URL)" sqlx

help:
	@grep -hE '^[a-z-]+:.*?## .*$$' $(firstword $(MAKEFILE_LIST)) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-14s %s\n", $$1, $$2}'

install-cli: ## Install the sqlx CLI with SQLite support (needed for migrations)
	cargo install sqlx-cli --no-default-features --features sqlite,rustls

db: ## Create the local database and apply every migration
	mkdir -p $(dir $(DB_FILE))
	$(SQLX) database create
	$(MAKE) migrate

db-reset: ## Delete the local database and migrate again
	rm -f $(DB_FILE) $(DB_FILE)-wal $(DB_FILE)-shm
	$(MAKE) db

migration: ## Add an empty migration: make migration name=what_it_does
	@test -n "$(name)" || (echo "usage: make migration name=what_it_does" && exit 1)
	$(SQLX) migrate add --source $(MIGRATIONS) $(name)

migrate: ## Apply the pending migrations, then write schema.sql again
	$(SQLX) migrate run --source $(MIGRATIONS)
	$(MAKE) schema

schema: ## Write crates/bunker-api/schema.sql from the local database
	@test -f $(DB_FILE) || (echo "no database at $(DB_FILE), run make db" && exit 1)
	@printf '%s\n' \
		'-- Generated by `make schema` from the migrated database. Do not edit.' \
		'-- This file is the readable source of truth for the structure. The' \
		'-- migrations are the source of truth for how to get there.' \
		'' > $(SCHEMA)
	@sqlite3 $(DB_FILE) \
		"select sql || ';' || char(10) from sqlite_master where sql is not null and name not like 'sqlite_%' and name != '_sqlx_migrations' order by name" \
		>> $(SCHEMA)

admin: $(DB_FILE) ## Promote a player to admin: make admin handle=dave
	@test -n "$(handle)" || (echo "usage: make admin handle=dave" && exit 1)
	sqlite3 -cmd ".parameter set :handle '$(handle)'" $(DB_FILE) "update players set role = 'admin' where handle = :handle collate nocase; select changes() || ' player(s) promoted';"

OPENAPI := $(API_DIR)/openapi.json

openapi: $(DB_FILE) ## Write crates/bunker-api/openapi.json from the route annotations
	cargo run -q -p bunker-api -- openapi > $(OPENAPI)

api-types: openapi ## Generate web/src/lib/api-types.d.ts from openapi.json
	pnpm -C web exec openapi-typescript ../$(OPENAPI) -o src/lib/api-types.d.ts
	pnpm -C web exec oxfmt src/lib/api-types.d.ts

seed: ## Fill the running dev API with 30 players and an open tournament of 23 entrants
	API_URL=http://127.0.0.1:$(PORT) DB_FILE=$(DB_FILE) scripts/seed-dev.sh

dev: ## Build and restart the API after each save (needs cargo install cargo-watch)
	cargo watch --why --clear --exec 'run -p bunker-api'

run: ## Start the API
	cargo run -p bunker-api

$(DB_FILE):
	$(MAKE) db

test: $(DB_FILE) ## Run every Rust test. Each test brings its own SQLite file
	cargo test --workspace

lint: $(DB_FILE) ## Run clippy. A warning is an error
	cargo clippy --workspace --all-targets -- -D warnings

fmt: ## Format the code
	cargo fmt --all

checklist: ## Run this one command before you report that a Rust task is complete
	cargo fmt --all
	$(MAKE) lint
	$(MAKE) test

web-dev: ## Start the Astro dev server
	pnpm -C web dev

web-build: ## Build the Astro site
	pnpm -C web build

web-check: ## Format check, lint, type check and build for the site
	pnpm -C web exec oxfmt --check
	pnpm -C web lint
	pnpm -C web exec astro check
	pnpm -C web build

web-e2e: $(DB_FILE) ## Playwright end to end tests against a fresh API and the dev site
	pnpm -C web exec playwright test
