/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/players": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["list_players"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/admin/players/{id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        delete: operations["delete_player"]
        options?: never
        head?: never
        patch: operations["set_role"]
        trace?: never
    }
    "/api/admin/players/{id}/password-reset": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["reset_password"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/auth/login": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["login"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/auth/signup": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["signup"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/me": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["me"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/me/password": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations["change_password"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/players": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["list_players"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/api/players/{handle}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["get_player"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/health/live": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["live"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/health/ready": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations["ready"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /** @description What `/api/me` answers: the public player plus what only the owner sees. */
        Account: {
            /**
             * @description Set after an admin reset. The API only reports it: the site forces the
             *     change before it shows any other page.
             */
            mustChangePassword: boolean
            player: components["schemas"]["Player"]
        }
        /** @description The one shape every failure has on the wire. */
        ApiErrorBody: {
            /** @description The chain of causes. It is absent if a user can see the response. */
            cause?: string | null
            code: components["schemas"]["ErrorCode"]
            message: string
            /** Format: int32 */
            status: number
        }
        /**
         * @description Each error code the API can answer with. A client selects on these names, so
         *     they are part of the contract.
         *
         *     Two steps make a response from an error: `ServiceError::public` below selects
         *     the code, and `From<ErrorCode> for StatusCode` in `server.rs` selects the
         *     status.
         * @enum {string}
         */
        ErrorCode:
            | "GenericError"
            | "ServiceUnavailable"
            | "ItemNotFound"
            | "HandleTaken"
            | "InvalidCredentials"
            | "Unauthorized"
            | "Forbidden"
            | "WrongPassword"
            | "InvalidRequest"
            | "UnprocessableRequest"
            | "UnsupportedMediaType"
            | "PayloadTooLarge"
            | "RouteNotFound"
            | "MethodNotAllowed"
        /**
         * @description What the players table stores: the grid and the color. Generated one time at
         *     signup and then read, never recomputed.
         */
        Glyph: {
            bits: components["schemas"]["GlyphBits"]
            color: components["schemas"]["GlyphColor"]
        }
        /** @description Row-major 5x5 grid as one integer. Bit 0 is the top left cell. */
        GlyphBits: number
        /**
         * @description One of the twelve palette colors. It serializes as the hex string the web
         *     uses, so a stored value and a rendered value never disagree.
         * @enum {string}
         */
        GlyphColor:
            | "#ffb000"
            | "#4fd1e0"
            | "#b48cff"
            | "#ff6b57"
            | "#9dff57"
            | "#ff5cc8"
            | "#cfe7ff"
            | "#ffd75c"
            | "#2dd4bf"
            | "#ff8c42"
            | "#7cc4ff"
            | "#7ef5c0"
        Handle: string
        Health: {
            status: string
            version: string
        }
        /** @description Request body of `POST /api/auth/login`. */
        LoginRequest: {
            handle: components["schemas"]["Handle"]
            password: components["schemas"]["Password"]
        }
        /** @description One page of results, and the totals a client needs for a pager. */
        Paginated_Player: {
            items: {
                /** Format: date-time */
                createdAt: string
                glyph: components["schemas"]["Glyph"]
                handle: components["schemas"]["Handle"]
                id: components["schemas"]["PlayerId"]
                role: components["schemas"]["Role"]
            }[]
            /** Format: int32 */
            page: number
            /** Format: int32 */
            pageSize: number
            /**
             * Format: int64
             * @description Every row that matches, ignoring the window.
             */
            total: number
            /** Format: int64 */
            totalPages: number
        }
        /** Format: password */
        Password: string
        /** @description Request body of `POST /api/me/password`. */
        PasswordChange: {
            currentPassword: components["schemas"]["Password"]
            newPassword: components["schemas"]["Password"]
        }
        /** @description A player, as the API shows it to anyone. It holds no credential. */
        Player: {
            /** Format: date-time */
            createdAt: string
            glyph: components["schemas"]["Glyph"]
            handle: components["schemas"]["Handle"]
            id: components["schemas"]["PlayerId"]
            role: components["schemas"]["Role"]
        }
        /** Format: uuid */
        PlayerId: string
        /**
         * @description What a player may do. Admins reach the backoffice and manage players.
         * @enum {string}
         */
        Role: "user" | "admin"
        /** @description Request body of `PATCH /api/admin/players/{id}`. */
        RoleUpdate: {
            role: components["schemas"]["Role"]
        }
        /** @description Request body of `POST /api/auth/signup`. */
        SignupRequest: {
            handle: components["schemas"]["Handle"]
            password: components["schemas"]["Password"]
        }
        /**
         * @description The answer to an admin password reset. Shown once, never stored in clear, and
         *     never printed: `Debug` redacts it like [`Password`].
         */
        TemporaryPassword: {
            temporaryPassword: string
        }
        /** @description The answer to a signup or a login. The token is a bearer JWT. */
        TokenResponse: {
            /** Format: date-time */
            expiresAt: string
            token: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    list_players: {
        parameters: {
            query?: {
                page?: number
                pageSize?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Paginated_Player"]
                }
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            403: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    delete_player: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: components["schemas"]["PlayerId"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            /** @description Not an admin, or the admin's own account */
            403: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    set_role: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: components["schemas"]["PlayerId"]
            }
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Player"]
                }
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            /** @description Not an admin, or the admin's own account */
            403: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            404: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    reset_password: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: components["schemas"]["PlayerId"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"]
                }
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            403: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            404: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    login: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"]
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TokenResponse"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    signup: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"]
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TokenResponse"]
                }
            }
            409: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    me: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Account"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    change_password: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"]
            }
        }
        responses: {
            /** @description A fresh token. Older tokens are refused from now on */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TokenResponse"]
                }
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    list_players: {
        parameters: {
            query?: {
                page?: number
                pageSize?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Paginated_Player"]
                }
            }
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    get_player: {
        parameters: {
            query?: never
            header?: never
            path: {
                handle: components["schemas"]["Handle"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Player"]
                }
            }
            404: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
    live: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Health"]
                }
            }
        }
    }
    ready: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Health"]
                }
            }
            503: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"]
                }
            }
        }
    }
}
