-- Generated by `make schema` from the migrated database. Do not edit.
-- This file is the readable source of truth for the structure. The
-- migrations are the source of truth for how to get there.

CREATE TABLE matches (
    id            text primary key check (length(id) = 36),
    tournament_id text not null references tournaments(id) on delete cascade,
    round         integer not null check (round >= 1),
    slot          integer not null check (slot >= 0),
    entrant_a     text,
    entrant_b     text,
    winner        text,
    unique (tournament_id, round, slot),
    check (winner is null or winner = entrant_a or winner = entrant_b),
    foreign key (tournament_id, entrant_a) references tournament_entrants (tournament_id, id),
    foreign key (tournament_id, entrant_b) references tournament_entrants (tournament_id, id),
    foreign key (tournament_id, winner) references tournament_entrants (tournament_id, id)
) strict;

CREATE VIEW player_standings as
select p.id as player_id,
       coalesce(sum(e.amount), 0) as cycles,
       rank() over (order by coalesce(sum(e.amount), 0) desc) as place,
       count(*) over () as players
from players p
left join point_entries e on e.player_id = p.id
group by p.id;

CREATE TABLE players (
    id            text primary key
                  check (length(id) = 36),
    handle        text not null unique collate nocase
                  check (length(handle) between 3 and 20
                         and handle not glob '*[^A-Za-z0-9_.-]*'),
    password_hash text not null,
    glyph_bits    integer not null
                  check (glyph_bits between 0 and 33554431),
    glyph_color   text not null
                  check (glyph_color in (
                      '#ffb000', '#4fd1e0', '#b48cff', '#ff6b57',
                      '#9dff57', '#ff5cc8', '#cfe7ff', '#ffd75c',
                      '#2dd4bf', '#ff8c42', '#7cc4ff', '#7ef5c0'
                  )),
    -- Unix time in microseconds. An integer sorts correctly, a formatted text
    -- with a trimmed fraction does not.
    created_at    integer not null
                  check (created_at > 0)
, role text not null default 'user'
    check (role in ('user', 'admin')), must_change_password integer not null default 0
    check (must_change_password in (0, 1)), credentials_changed_at integer not null default 0
    check (credentials_changed_at >= 0)) strict;

CREATE TABLE point_entries (
    id            text primary key check (length(id) = 36),
    player_id     text not null references players(id) on delete cascade,
    amount        integer not null check (amount != 0 and abs(amount) <= 10000),
    kind          text not null
                  check (kind in ('tournament_entry', 'match_win', 'champion', 'finalist',
                                  'semifinalist', 'adjustment')),
    -- What paid, inside the kind: the tournament for an entry or a placement,
    -- the match for a win, the row itself for an adjustment. Never null, so the
    -- unique index below holds for every kind, including the ones to come.
    source_ref    text not null check (length(source_ref) > 0),
    tournament_id text references tournaments(id) on delete cascade,
    note          text check (note is null or length(note) between 1 and 200),
    created_by    text references players(id) on delete set null,
    created_at    integer not null check (created_at > 0),
    -- Only an admin takes cycles away, and only with a reason.
    check (kind = 'adjustment' or amount > 0),
    check (kind != 'adjustment' or note is not null),
    -- A source pays one time however often the write is retried.
    unique (kind, player_id, source_ref)
) strict;

CREATE INDEX point_entries_player on point_entries (player_id, created_at desc);

CREATE TABLE tournament_entrants (
    id            text primary key check (length(id) = 36),
    tournament_id text not null references tournaments(id) on delete cascade,
    -- Null once the player deleted their account, so an old bracket keeps its
    -- shape. A team column can sit next to this one later.
    player_id     text references players(id) on delete set null,
    seed          integer check (seed is null or seed >= 1),
    registered_at integer not null check (registered_at > 0), skill integer check (skill is null or skill between 1 and 5),
    unique (tournament_id, player_id),
    -- Lets a match reference an entrant of its own tournament only.
    unique (tournament_id, id)
) strict;

CREATE INDEX tournament_entrants_player on tournament_entrants (player_id);

CREATE TABLE tournaments (
    id                     text primary key check (length(id) = 36),
    name                   text not null check (length(name) between 1 and 60),
    game                   text not null check (length(game) between 1 and 40),
    mode                   text not null check (length(mode) between 1 and 30),
    description            text not null check (length(description) <= 1000),
    date                   text not null
                           check (date glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
    registration_closes_at integer not null check (registration_closes_at > 0),
    status                 text not null default 'draft'
                           check (status in ('draft', 'open', 'live', 'concluded')),
    -- Only a concluded tournament has a winner. That the entrant belongs to this
    -- tournament is checked by the service: a CHECK cannot read another row.
    winner_entrant_id      text references tournament_entrants(id) on delete set null,
    created_at             integer not null check (created_at > 0),
    check (status = 'concluded' or winner_entrant_id is null)
) strict;

